version: "3.9"

services:
  backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.prod
    environment:
      - NODE_ENV=production
      - PORT=3001
    # depends_on:
    #   - db
    restart: always

  # db:
  #   image: mysql:8
  #   container_name: notes-db
  #   restart: always
  #   env_file:
  #     - .env.prod
  #   volumes:
  #     - db_data:/var/lib/mysql

  # nginx:
  #   image: nginx:latest
  #   container_name: notes-nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

# volumes:
#   db_data:
